workflows:
  version: 2
  main:
    jobs:
      - build


version: 2
jobs:
  build:
    machine:
      enabled: true
    working_directory: ~/project
    steps:
      - checkout
      - run:
          name: "Build Docker Images"
          command: ./build-images.sh
      - deploy:
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              docker login -u  $DOCKER_USER -p $DOCKER_PASS
              docker push cibuilds/hugo
            fi
