version: 2.1

workflows:
  main:
    jobs:
      - build-releases:
          context: org-global
  nightly-build:
    triggers:
      - schedule:
          cron: "0 6 * * *"
          filters:
            branches:
              only: master
    jobs:
      - build-nightly:
          context: org-global

jobs:
  build-releases:
    machine: true
    steps:
      - checkout
      - run:
          name: "Build Docker Images"
          command: ./build-images.sh
      - deploy:
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
            
              echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin

              if git log -1 --pretty=%s | grep "\[release\]"; then
                echo "Starting a release"
                docker push cibuilds/hugo
              else
                echo "Just publishing an edge image"
                docker tag cibuilds/hugo:latest cibuilds/hugo:edge
                docker push cibuilds/hugo:edge
              fi
            fi
  build-nightly:
    machine: true
    steps:
      - checkout
      - run:
          name: "Build Nightly Docker Image"
          command: ./build-nightly-image.sh
      - run:
          command: |
            echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin
            docker push cibuilds/hugo:nightly
