version: 2.1

workflows:
  main:
    jobs:
      - build-releases
      - build-nightly
  nightly-build:
    triggers:
      - schedule:
          cron: "0 6 * * *"
          filters:
            branches:
              only: master
    jobs:
      - build-nightly

jobs:
  build-releases:
    machine: true
    steps:
      - checkout
      - run:
          name: "Build Docker Images"
          command: ./build-images.sh
      - deploy:
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              docker login -u  $DOCKER_USER -p $DOCKER_PASS
              docker push cibuilds/hugo
            fi
  build-nightly:
    machine: true
    steps:
      - checkout
      - run:
          name: "Build Nightly Docker Image"
          command: ./build-nightly-image.sh
      - run:
          command: |
            docker login -u $DOCKER_USER -p $DOCKER_PASS
            docker push cibuilds/hugo:nightly
